Move redirect to stderr into error log function

diff --git a/gh-skeleton b/gh-skeleton
--- a/gh-skeleton
+++ b/gh-skeleton
@@ -26,12 +26,12 @@ log_warn() {
 }
 
 log_error() {
-  echo -e "${RED}! $*${RESET}"
+  echo -e "${RED}! $*${RESET}" >&2
 }
 
 # Determine if an executable is in the PATH
 if ! type -p perl > /dev/null; then
-  log_error "Perl not found on the system and is required" >&2
+  log_error "Perl not found on the system and is required"
   exit 1
 fi
 
