Add automation for as many steps as possible
- Requires an authenticated gh user to use clone sub-command.
- Add ability to specify destination organization.
- Attemps to create the remote repository.
- Handles remote repository already existing.
- Outputs manual steps for user to folllow if remote creation fails.
- Handles gh cli adding its own origins.
- Commits lineage.yml to develop branch.
- Commits search and replace to first-commits so first PR isn't empty.

diff --git a/gh-skeleton b/gh-skeleton
--- a/gh-skeleton
+++ b/gh-skeleton
@@ -1,10 +1,11 @@
-#!/bin/bash
+#!/usr/bin/env bash
 set -o nounset
 set -o errexit
 set -o pipefail
 
-# Default organization to search for skeletons
-ORGANIZATION="cisagov"
+# Default organizations
+DEST_ORG="cisagov"
+SRC_ORG="cisagov"
 
 # Define terminal colors for use in logger functions
 BLUE="\x1B[34m"
@@ -45,17 +46,18 @@ Usage:
   gh skeleton clone [options] <parent-repo-name> <new-repo-name>
 
 Options:
-  -c --change-dir=<dir>  Create clone in this directory.
-  -h --help              Show this message.
-  -o --org=<name>        Organization to search [default: ${ORGANIZATION}].
+  -c --change-dir=<dir> Create clone in this directory.
+  -d --dest-org=<name>  Organization to create clone into [default: ${DEST_ORG}].
+  -h --help             Show this message.
+  -s --src-org=<name>   Organization to search for skeletons [default: ${SRC_ORG}].
 END_OF_LINE
 )
 
 print_available_skeletons() {
-  org_name=$1
+  src_org=$1
   QUERY="
   query {
-    search(query: \"org:$org_name topic:skeleton archived:false\", type: REPOSITORY, first: 100) {
+    search(query: \"org:$src_org topic:skeleton archived:false\", type: REPOSITORY, first: 100) {
       repositoryCount
       edges {
         node {
@@ -78,7 +80,7 @@ print_available_skeletons() {
     {{- end -}}
   '
 
-  echo "Available skeletons in $org_name:"
+  echo "Available skeletons in $src_org:"
   echo
   exec gh api graphql \
     --raw-field query="${QUERY}" --paginate \
@@ -86,52 +88,106 @@ print_available_skeletons() {
 }
 
 clone_repo() {
-  parent_repo=$1
-  new_repo=$2
-  org_name=$3
+  src_repo=$1
+  dest_repo=$2
+  src_org=$3
+  dest_org=$4
+
+  # Before we continue check to see if the user is logged in. If there is no
+  # currently authenticated user gh will ask the user to run the "gh auth login"
+  # command and exit with return code 4.  This will cause this script to halt.
+  username=$(gh api user --jq '.login')
+
+  # If we got here we know we have an authenticated user.
+  log_ok "You are logged into GitHub as ${username}."
+
+  log_info "Creating ${dest_org}/${dest_repo} from skeleton ${src_org}/${src_repo}."
 
   log_info "Clone skeleton remote repository to the new local repository."
-  git clone --origin "${parent_repo}" git@github.com:"${org_name}/${parent_repo}".git "${new_repo}"
+  git clone --origin "${src_repo}" git@github.com:"${src_org}/${src_repo}".git "${dest_repo}"
 
-  cd "${new_repo}"
+  cd "${dest_repo}"
 
   log_info "Disable pushing to the upstream (parent) repository."
-  git remote set-url --push "${parent_repo}" no_push
-
-  log_info "Add a new remote origin for the this repository."
-  git remote add origin git@github.com:"${org_name}/${new_repo}".git
-
-  log_info "Search and replace repository name in source files."
-  find . \( ! -regex '.*/\.git/.*' \) -type f -exec \
-    perl -pi -e "s/${parent_repo}/${new_repo}/g" {} \;
+  git remote set-url --push "${src_repo}" no_push
 
   log_info "Create the lineage.yml file."
   cat << END_OF_LINE > .github/lineage.yml
 ---
 lineage:
   skeleton:
-    remote-url: https://github.com/${org_name}/${parent_repo}.git
+    remote-url: https://github.com/${src_org}/${src_repo}.git
 version: '1'
 END_OF_LINE
 
   log_info "Stage modified files."
   git add --verbose .
 
-  log_info "Commit staged files to the new repository."
+  log_info "Commit staged files to the develop branch."
+  git commit --message "Adding lineage configuration"
+
+  log_info "Creating first-commits branch."
+  git checkout -b first-commits
+
+  log_info "Search and replace repository name in source files."
+  find . \( ! -regex '.*/\.git/.*' \) -type f -exec \
+    perl -pi -e "s/${src_repo}/${dest_repo}/g" {} \;
+
+  log_info "Stage modified files."
+  git add --verbose .
+
+  log_info "Commit staged files to the first-commits branch."
   git commit --message "Rename repository references after clone"
 
-  log_ok "Success!"
+  remote_repo_status="unknown"
+  log_info "Checking for remote repository ${dest_org}/${dest_repo}."
+  remote_repo_name=$(gh repo view --json name --jq ".name" "${dest_org}/${dest_repo}") || :
+  if [[ -n ${remote_repo_name} ]]; then
+    log_ok "${dest_org}/${dest_repo} exists."
+    remote_repo_status="existed"
+  else
+    log_warn "${dest_org}/${dest_repo} does not yet exist."
+    log_info "Attempting to create a new remote repository."
+    # Note that gh will attempt to add the remote origin and will throw an error
+    # if it already exists.  We'll add the origin later if gh fails.
+    remote_repo_status="created"
+    gh repo create --public --confirm "${dest_org}/${dest_repo}" || remote_repo_status="failed"
+  fi
 
-  # Echo instuctions to user
-  cat << END_OF_LINE
-The repository "${parent_repo}" has been cloned and renamed to "${new_repo}".
-Use the following commands to push the new repository to GitHub and create a pull request:
-    cd ${CHANGE_DIR:+${CHANGE_DIR}/}${new_repo}
-    git checkout -b first-commits
+  # Handle the different outcomes of the remote repository.
+  case $remote_repo_status in
+    created)
+      log_ok "The remote repository ${dest_org}/${dest_repo} was successfully created."
+      ;;&
+    existed | failed)
+      log_info "Add a new remote origin for the this repository."
+      # We can add the remote origin now since gh was unable to do it.
+      git remote add origin git@github.com:"${dest_org}/${dest_repo}".git
+      ;;&
+    created | existed)
+      log_info "Pushing develop and first-commit branches to the remote."
+      git push origin develop first-commits --set-upstream
+      log_info "Opening a new pull request for the first-commits branch."
+      log_info "If prompted, please select ${dest_org}/${dest_repo} as the base repository."
+      gh pr create --title "First commits" --assignee=@me --web
+      log_ok "Success!"
+      ;;
+    failed)
+      log_warn "The remote repository ${dest_org}/${dest_repo} counld not be created."
+      cat << END_OF_LINE
+${dest_org}/${dest_repo} was created locally from the ${src_repo} skeleton.
+A remote repository was unable to be created automatically.
+Please manually create the ${dest_org}/${dest_repo} repository on GitHub.
+
+Once ${dest_org}/${dest_repo} is created use the following commands to push
+the local repository to the remote and create the initial pull request:
+    cd ${CHANGE_DIR:+${CHANGE_DIR}/}${dest_repo}
     git push origin develop first-commits --set-upstream
     gh pr create --title "First commits" --assignee=@me --web
 
 END_OF_LINE
+      ;;
+  esac
 }
 
 # Initialize positional parameters and flag variables
@@ -145,12 +201,16 @@ while (("$#")); do
       CHANGE_DIR="$2"
       shift
       ;;
+    -d | --dest-org)
+      DEST_ORG="$2"
+      shift
+      ;;
     -h | --help)
       echo "${USAGE}"
       exit 0
       ;;
-    -o | --org)
-      ORGANIZATION="$2"
+    -s | --src-org)
+      SRC_ORG="$2"
       shift
       ;;
     -*) # unsupported flags
@@ -177,14 +237,14 @@ case "$1" in
     fi
     if [[ -n ${CHANGE_DIR} ]]; then
       pushd "${CHANGE_DIR}" 1> /dev/null
-      clone_repo "$2" "$3" "${ORGANIZATION}"
+      clone_repo "$2" "$3" "${SRC_ORG}" "${DEST_ORG}"
       popd 1> /dev/null
     else
-      clone_repo "$2" "$3" "${ORGANIZATION}"
+      clone_repo "$2" "$3" "${SRC_ORG}" "${DEST_ORG}"
     fi
     ;;
   list)
-    print_available_skeletons "${ORGANIZATION}"
+    print_available_skeletons "${SRC_ORG}"
     ;;
   *)
     echo "Unknown command $1"
